using System.Globalization;
using System.Text;

namespace LabControl.Shared.Jobs;

/// <summary>Which built-in script the development-only <i>Run test script</i> action sends (D-31 item 3).</summary>
public enum TestScriptKind
{
    /// <summary>Prints 100 numbered lines and exits with code 3 — ROADMAP M2's first script criterion.</summary>
    HundredLines = 0,

    /// <summary>Prints one line and then sleeps for ever — must be killed at the timeout and reported.</summary>
    Hang = 1,

    /// <summary>Prints the account, session and working directory it runs in — proves <c>as: user</c> versus SYSTEM.</summary>
    WhoAmI = 2,
}

/// <summary>
/// The scripts the console has built in for M2's acceptance criteria, in both shells.
/// They exist so the agent's <c>run_script</c> can be proved on the VM before the teacher's
/// script library is built in M4; the simulator recognises the same constructs
/// (<c>FakeAgent</c>) so the console can be developed against them on the Mac.
/// </summary>
public static class TestScripts
{
    public const int HundredLinesCount = 100;
    public const int HundredLinesExitCode = 3;

    public static string NameOf(TestScriptKind kind) => kind switch
    {
        TestScriptKind.HundredLines => "test-100-lines",
        TestScriptKind.Hang => "test-hang",
        TestScriptKind.WhoAmI => "test-whoami",
        _ => "test",
    };

    public static string Text(TestScriptKind kind, ScriptShell shell) => shell == ScriptShell.Cmd ? Cmd(kind) : PowerShell(kind);

    private static string PowerShell(TestScriptKind kind)
    {
        var text = new StringBuilder();
        text.AppendLine("# LabControl built-in test script (M2). Generated by the console; not for editing.");

        switch (kind)
        {
            case TestScriptKind.HundredLines:
                text.AppendLine(CultureInfo.InvariantCulture, $"for ($i = 1; $i -le {HundredLinesCount}; $i++) {{ Write-Output \"line $i of {HundredLinesCount}\" }}");
                text.AppendLine(CultureInfo.InvariantCulture, $"exit {HundredLinesExitCode}");
                break;

            case TestScriptKind.Hang:
                text.AppendLine("Write-Output \"hanging now; the agent must kill this at the timeout\"");
                text.AppendLine("while ($true) { Start-Sleep -Seconds 3600 }");
                break;

            case TestScriptKind.WhoAmI:
                text.AppendLine("Write-Output \"user: $env:USERNAME ($([Security.Principal.WindowsIdentity]::GetCurrent().Name))\"");
                text.AppendLine("Write-Output \"session: $((Get-Process -Id $PID).SessionId)\"");
                text.AppendLine("Write-Output \"interactive: $([Environment]::UserInteractive)\"");
                text.AppendLine("Write-Output \"directory: $PWD\"");
                text.AppendLine("Write-Output \"script: $PSCommandPath\"");
                text.AppendLine("Write-Output \"powershell: $($PSVersionTable.PSVersion)\"");
                text.AppendLine("Write-Output \"cyrillic check: привіт, лабораторіє\"");
                text.AppendLine("exit 0");
                break;
        }

        return text.ToString();
    }

    private static string Cmd(TestScriptKind kind)
    {
        var text = new StringBuilder();
        text.AppendLine("@echo off");
        text.AppendLine("rem LabControl built-in test script (M2). Generated by the console; not for editing.");

        switch (kind)
        {
            case TestScriptKind.HundredLines:
                text.AppendLine(CultureInfo.InvariantCulture, $"for /l %%i in (1,1,{HundredLinesCount}) do echo line %%i of {HundredLinesCount}");
                text.AppendLine(CultureInfo.InvariantCulture, $"exit /b {HundredLinesExitCode}");
                break;

            case TestScriptKind.Hang:
                text.AppendLine("echo hanging now; the agent must kill this at the timeout");
                text.AppendLine(":loop");
                text.AppendLine("timeout /t 3600 /nobreak >nul");
                text.AppendLine("goto loop");
                break;

            case TestScriptKind.WhoAmI:
                text.AppendLine("echo user: %USERNAME%");
                text.AppendLine("for /f \"tokens=*\" %%u in ('whoami') do echo account: %%u");
                // %SESSIONNAME% is unset for anything a service starts; tasklist knows the session.
                text.AppendLine("echo session name: %SESSIONNAME%");
                text.AppendLine("for /f \"tokens=2,4 delims=,\" %%a in ('tasklist /fo csv /nh /fi \"imagename eq cmd.exe\"') do echo cmd.exe pid %%~a in session %%~b");
                text.AppendLine("echo directory: %CD%");
                text.AppendLine("echo script: %~f0");
                text.AppendLine("echo cyrillic check: привіт, лабораторіє");
                text.AppendLine("exit /b 0");
                break;
        }

        return text.ToString();
    }
}
