namespace LabControl.Shared.Persistence;

/// <summary>
/// <c>agent.json</c> — everything a student PC knows (ARCHITECTURE §3.3): its lab, its own
/// identity, its number, and the revocations it has been shown. No lab secret, no
/// passphrase, no shared symmetric key, and nothing about any other PC.
/// </summary>
public sealed class AgentConfigDocument : ISchemaVersioned
{
    public static readonly SchemaMigrations Migrations = new(Defaults.AgentConfigSchemaVersion);

    public int SchemaVersion { get; set; } = Defaults.AgentConfigSchemaVersion;

    public string LabId { get; set; } = string.Empty;

    /// <summary>Generated by Setup at install time and never changed by anything else.</summary>
    public string AgentId { get; set; } = string.Empty;

    /// <summary>The sticker on the PC, answered once during installation.</summary>
    public int Number { get; set; }

    public string Hostname { get; set; } = string.Empty;

    public string Mac { get; set; } = string.Empty;

    /// <summary>The single-use code, kept until enrollment succeeds and then cleared.</summary>
    public string? EnrollmentCode { get; set; }

    /// <summary>
    /// Fallback for a network that drops broadcasts (ARCHITECTURE §3.4). Empty in the normal
    /// case: the console moves and the beacon is how the PC follows it.
    /// </summary>
    public string? ConsoleHost { get; set; }

    public int ConsolePort { get; set; } = Defaults.ConsolePort;

    /// <summary>
    /// The console instance this PC was last linked to. Reported in <c>Hello</c> so a
    /// console can name the PCs the other teacher machine holds (D-21).
    /// </summary>
    public string? LastInstanceId { get; set; }

    /// <summary>
    /// The union of every signed revocation this PC has seen. Sent right after <c>Hello</c>,
    /// so a console that was switched off when another teacher machine revoked something
    /// learns of it from the first agent that connects (D-21).
    /// </summary>
    public List<RevocationRecord> Revocations { get; set; } = [];
}
