<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><OutputType>Exe</OutputType><TargetFramework>net10.0-windows</TargetFramework><AssemblyName>LabControl.InteractiveUninstall</AssemblyName><UseWindowsForms>true</UseWindowsForms></PropertyGroup>
  <ItemGroup><ProjectReference Include="../../../src/LabControl.Setup/LabControl.Setup.csproj" /></ItemGroup>
</Project>
